/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ROSTER"
 * 	found in "/Users/proger/cg/chat/src/ROSTER.asn1"
 */

#include "Adr.h"

static asn_TYPE_member_t asn_MBR_dst_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct dst, choice.muc),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MUC,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"muc"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct dst, choice.p2p),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_P2P,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"p2p"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_dst_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* muc */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* p2p */
};
static asn_CHOICE_specifics_t asn_SPC_dst_specs_3 = {
	sizeof(struct dst),
	offsetof(struct dst, _asn_ctx),
	offsetof(struct dst, present),
	sizeof(((struct dst *)0)->present),
	asn_MAP_dst_tag2el_3,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_dst_3 = {
	"dst",
	"dst",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_dst_3,
	2,	/* Elements count */
	&asn_SPC_dst_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Adr_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Adr, src),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"src"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Adr, dst),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_dst_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"dst"
		},
};
static const ber_tlv_tag_t asn_DEF_Adr_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Adr_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 0, 0, 0 }, /* src */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, 0, 0 }, /* muc */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* p2p */
};
static asn_SEQUENCE_specifics_t asn_SPC_Adr_specs_1 = {
	sizeof(struct Adr),
	offsetof(struct Adr, _asn_ctx),
	asn_MAP_Adr_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Adr = {
	"Adr",
	"Adr",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Adr_tags_1,
	sizeof(asn_DEF_Adr_tags_1)
		/sizeof(asn_DEF_Adr_tags_1[0]), /* 1 */
	asn_DEF_Adr_tags_1,	/* Same as above */
	sizeof(asn_DEF_Adr_tags_1)
		/sizeof(asn_DEF_Adr_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Adr_1,
	2,	/* Elements count */
	&asn_SPC_Adr_specs_1	/* Additional specs */
};

