/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ROSTER"
 * 	found in "/Users/proger/cg/chat/src/ROSTER.asn1"
 * 	`asn1c -pdu=all`
 */

#ifndef	_Bin_H_
#define	_Bin_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Bin */
typedef struct Bin {
	OCTET_STRING_t	 id;
	OCTET_STRING_t	 mime;
	OCTET_STRING_t	 payload;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Bin_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Bin;

#ifdef __cplusplus
}
#endif

#endif	/* _Bin_H_ */
#include <asn_internal.h>
