/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ROSTER"
 * 	found in "/Users/proger/cg/chat/src/ROSTER.asn1"
 */

#ifndef	_Nak_H_
#define	_Nak_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Nak */
typedef struct Nak {
	OCTET_STRING_t	 key;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Nak_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Nak;

#ifdef __cplusplus
}
#endif

#endif	/* _Nak_H_ */
#include <asn_internal.h>
