/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ROSTER"
 * 	found in "/Users/proger/cg/chat/src/ROSTER.asn1"
 */

#ifndef	_P2P_H_
#define	_P2P_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* P2P */
typedef struct P2P {
	OCTET_STRING_t	 dst;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} P2P_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_P2P;

#ifdef __cplusplus
}
#endif

#endif	/* _P2P_H_ */
#include <asn_internal.h>
