/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_MUC;
extern struct asn_TYPE_descriptor_s asn_DEF_P2P;
extern struct asn_TYPE_descriptor_s asn_DEF_Ack;
extern struct asn_TYPE_descriptor_s asn_DEF_Bin;
extern struct asn_TYPE_descriptor_s asn_DEF_Typ;
extern struct asn_TYPE_descriptor_s asn_DEF_Adr;
extern struct asn_TYPE_descriptor_s asn_DEF_Msg;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module ROSTER in /Users/proger/cg/chat/src/ROSTER.asn1 */
	&asn_DEF_MUC,	
	&asn_DEF_P2P,	
	&asn_DEF_Ack,	
	&asn_DEF_Bin,	
	&asn_DEF_Typ,	
	&asn_DEF_Adr,	
	&asn_DEF_Msg,	
	0
};

