/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ROSTER"
 * 	found in "/Users/proger/cg/chat/src/ROSTER.asn1"
 * 	`asn1c -pdu=all`
 */

#ifndef	_Typ_H_
#define	_Typ_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Typ {
	Typ_new	= 0,
	Typ_edit	= 1,
	Typ_delete	= 2
} e_Typ;

/* Typ */
typedef long	 Typ_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Typ;
asn_struct_free_f Typ_free;
asn_struct_print_f Typ_print;
asn_constr_check_f Typ_constraint;
ber_type_decoder_f Typ_decode_ber;
der_type_encoder_f Typ_encode_der;
xer_type_decoder_f Typ_decode_xer;
xer_type_encoder_f Typ_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Typ_H_ */
#include <asn_internal.h>
