%% Generated by the Erlang ASN.1 compiler. Version: 5.0.8
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module PKCS-10.

-ifndef(_PKCS_10_HRL_).
-define(_PKCS_10_HRL_, true).

-record('SubjectPublicKeyInfo', {
  algorithm,
  subjectPublicKey
}).

-record('Attribute', {
  type,
  values
}).

-record('CertificationRequestInfo', {
  version,
  subject,
  subjectPKInfo,
  attributes
}).

-record('CertificationRequestInfo_subjectPKInfo', {
  algorithm,
  subjectPublicKey
}).

-record('CertificationRequestInfo_subjectPKInfo_algorithm', {
  algorithm,
  parameters = asn1_NOVALUE
}).

-record('CertificationRequestInfo_attributes_SETOF', {
  type,
  values
}).

-record('CertificationRequest', {
  certificationRequestInfo,
  signatureAlgorithm,
  signature
}).

-record('CertificationRequest_signatureAlgorithm', {
  algorithm,
  parameters = asn1_NOVALUE
}).

-endif. %% _PKCS_10_HRL_
