%% Generated by the Erlang ASN.1 compiler version:3.0.2
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition,in module SMP

-ifndef(_SMP_HRL_).
-define(_SMP_HRL_, true).

-include_lib("kvs/include/kvs.hrl").

-record('Auth',{username, token, services}).
-record('Person',{?ITERATOR(feed), name, surname, username, status}).
-record('Presence',{size, userlist}).
-record('Friend',{id, user, status}).
-record('Confirm',{?ITERATOR(feed), user, type}).
-record('Private',{?ITERATOR(feed), author, body, status}).
-record('Typing',{author}).

-record('Room',{room, description, acl, settings}).
-record('Join',{user, room, answer}).
-record('Public',{?ITERATOR(feed), room, message, author}).

-record('Retrieve',{id, chat}).
-record('Mark',{id, room, status}).
-record('Search',{id, body, author}).

-endif. %% _SMP_HRL_
