%% Generated by the Erlang ASN.1 compiler version:3.0.2
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition,in module SMP



-ifndef(_SMP_HRL_).
-define(_SMP_HRL_, true).

-record('Auth',{
username, token, services}).

-record('Person',{
id, name, surname, username, status}).

-record('Presence',{
size, userlist}).

-record('Add',{
user, status}).

-record('Confirm',{
user, type}).

-record('Room',{
name, id}).

-record('Create',{
room, description, acl, settings}).

-record('Join',{
user, room, answer}).

-record('RoomEvent',{
id, room, message, author}).

-record('RoomMessage',{
id, author, room, body, status}).

-record('Message',{
id, author, body, status}).

-record('Typing',{
author}).

-record('Retrieve',{
id, chat}).

-record('Mark',{
id, room, status}).

-record('Search',{
id, body, author}).

-endif. %% _SMP_HRL_
