%% Generated by the Erlang ASN.1 compiler. Version: 5.0.8
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module ROSTER.

-ifndef(_ROSTER_HRL_).
-define(_ROSTER_HRL_, true).

-record('P2P', {
  dst
}).

-record('MUC', {
  dst
}).

-record('Adr', {
  src,
  dst
}).

-record('CSR', {
  der
}).

-record('CRT', {
  der
}).

-record('N2O', {
  tok
}).

-record('Ack', {
  lex
}).

-record('Nak', {
  key
}).

-record('Pub', {
  key,
  adr,
  tag,
  bin
}).

-record('Sub', {
  key,
  adr
}).

-endif. %% _ROSTER_HRL_
